# Generated by Django 3.2.9 on 2021-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211110_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='following',
        ),
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='last_loginobject',
        # ),
        # migrations.AddField(
        #     model_name='customuser',
        #     name='last_login',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        # ),
    ]
