# Generated by Django 3.2.9 on 2021-11-11 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211110_1409'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='last_loginobject',
        # ),
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.AddField(
        #     model_name='customuser',
        #     name='following',
        #     field=models.ManyToManyField(blank=True, related_name='followeing', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='customuser',
        #     name='last_login',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        # ),
    ]
